#!/usr/bin/env python3
"""Create a new driver/library skeleton.

Creates a directory at <relative-path>/<lib-name> (relative to current
working directory), with `include` and `src` subdirectories and a
header and source file populated with minimal templates.

Usage:
  ./create_new_drv.py <relative-path> <lib-name> [--force]

Example:
  ./create_new_drv.py components drv_foo

Options:
  --force   Overwrite files if they already exist
"""

from __future__ import annotations

import argparse
import datetime
import os
import re
import sys


def sanitize_identifier(name: str) -> str:
	"""Return a sanitized identifier: keep alnum, replace others with '_'."""
	return re.sub(r"[^0-9a-zA-Z]", "_", name)


HEADER_TEMPLATE = """/* {lib}.h - autogenerated {date} */

#ifndef {guard}
#define {guard}

#ifdef __cplusplus
extern "C" {{
#endif

void {init_fn}(void);

#ifdef __cplusplus
}}
#endif

#endif /* {guard} */
"""

SOURCE_TEMPLATE = """/* {lib}.c - autogenerated {date} */

#include "{lib}.h"
#include <stdio.h>

void {init_fn}(void) {{
	/* TODO: implement */
	(void)printf("{lib} initialized\n");
}}
"""


def write_file(path: str, content: str, force: bool) -> None:
	if os.path.exists(path) and not force:
		print(f"Skipping existing file: {path} (use --force to overwrite)")
		return
	with open(path, "w", encoding="utf-8") as f:
		f.write(content)
	print(f"Wrote: {path}")


def make_skeleton(rel_path: str, lib_name: str, force: bool = False) -> int:
	cwd = os.getcwd()
	target_base = os.path.normpath(os.path.join(cwd, rel_path, lib_name))

	include_dir = os.path.join(target_base, "includes")
	src_dir = os.path.join(target_base, "src")

	os.makedirs(include_dir, exist_ok=True)
	os.makedirs(src_dir, exist_ok=True)

	sanitized = sanitize_identifier(lib_name)
	guard = (sanitized + "_H").upper()
	init_fn = f"{sanitized}_init"
	today = datetime.date.today().isoformat()

	header_path = os.path.join(include_dir, f"{lib_name}.h")
	source_path = os.path.join(src_dir, f"{lib_name}.c")

	header_content = HEADER_TEMPLATE.format(lib=lib_name, guard=guard, init_fn=init_fn, date=today)
	source_content = SOURCE_TEMPLATE.format(lib=lib_name, init_fn=init_fn, date=today)

	write_file(header_path, header_content, force)
	write_file(source_path, source_content, force)

	print(f"Created library skeleton at: {target_base}")
	return 0


def parse_args(argv: list[str]) -> argparse.Namespace:
	p = argparse.ArgumentParser(description="Create a new driver/library skeleton")
	p.add_argument("relpath", help="Relative path from current directory where the lib folder will be created")
	p.add_argument("libname", help="Name of the library/folder to create")
	p.add_argument("--force", action="store_true", help="Overwrite files if they exist")
	return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
	argv = sys.argv[1:] if argv is None else argv
	args = parse_args(argv)
	return make_skeleton(args.relpath, args.libname, force=args.force)


if __name__ == "__main__":
	raise SystemExit(main())

