/* PCF8574_IoExp.h - autogenerated 2026-01-11 */

#ifndef PCF8574_IOEXP_H
#define PCF8574_IOEXP_H

#include <stdint.h>
#include "gpio_hal.h"
#include "i2c_hal.h"

typedef struct PCF8574_config_s PCF8574_handle_t;
typedef void (*IoEXPIntCB)(void);

typedef enum PCF8574_IoExp_pinValue_e
{
    IO_EXP_LOW,
    IO_EXP_HIGH
} PCF8574_IoExp_pinValue_t;

typedef enum PCF8574_IoExp_pinDirection_e
{
    IO_EXP_INPUT,
    IO_EXP_OUTPUT
} PCF8574_IoExp_pinDirection_t;

typedef struct PCF8574_config_s
{
    i2c_hal_bus_handle_t *i2c_bus_handle;
    i2c_hal_device_handle_t *i2c_device_handle;
    uint8_t max_pins; /*Max no of pins per port*/
    uint8_t max_port;
    gpio_hal_pin init_gpio;
} PCF8574_config_t;

typedef struct PCF8574_ctx_s{
    I2C_7BitAddress_t dev_address;
    i2c_hal_bus_handle_s i2c_bus_handle;
    i2c_hal_device_handle_t dev_handle;
    
}PCF8574_ctx_t;

typedef struct PCF8574_pin_config_s
{
    uint8_t pinNo;
    PCF8574_IoExp_pinDirection_t direction;
    PCF8574_IoExp_pinValue_t value;
} PCF8574_pin_config_t;

/*Fill the config structure before calling the init, init i2c and put the
i2c_hal_bus_handle as i2c_bus_handle in the config
and i2c_hal_device_handle created for PCF8574 in the i2c_device_handle of the config*/
int8_t PCF8574_IoExp_init(PCF8574_handle_t *handle, PCF8574_config_t *config);

int8_t PCF8574_IoExp_configPin(PCF8574_handle_t *, PCF8574_pin_config_t pin_config);
int8_t PCF8574_IoExp_setPin(PCF8574_handle_t *, uint8_t portNo, uint8_t pinNo, uint8_t value);
int8_t PCF8574_IoExp_setPort(PCF8574_handle_t *handle, uint8_t portNo, uint8_t value);

int8_t PCF8574_IoExp_readPin(PCF8574_handle_t *, uint8_t portNo, uint8_t pinNo, uint8_t *value);
int8_t PCF8574_IoExp_readPort(PCF8574_handle_t *handle, uint8_t portNo, uint8_t *value);

// esp_err_t i2c_hal_probe(i2c_hal_bus_handle_t *bus_handle, i2c_hal_device_handle_t *dev_handle);

#endif /* PCF8574_IOEXP_H */
