/* test_lib.h - autogenerated 2026-01-11 */

#ifndef TEST_LIB_H
#define TEST_LIB_H

#ifdef __cplusplus
extern "C" {
#endif

void test_lib_init(void);

#ifdef __cplusplus
}
#endif

#endif /* TEST_LIB_H */
